site_name: wmax641's docs
site_url: https://wmax641.website/personal-docs/
site_author: wmax641
site_description: wmax641's personal docs and notes
nav:
  - Systems Administration:
    - "Shell cheatsheet" : "sysadmin/shell_cheatsheet.md"
    - "jq cheatsheet" : "sysadmin/jq_cheatsheet.md"
    - "Certificates and OpenSSL" : "sysadmin/certs.md"
  - Systems Engineering:
    - "Docker" : "syseng/docker.md"
    - "Kubernetes/K8s" : "syseng/k8s.md"
    - "Wireguard" : "syseng/wireguard.md"
    - "Github Actions" : "syseng/githubactions.md"
  - Patterns:
    - "Dockerfile" : "patterns/docker.md"
    - "Kubernetes/K8s" : "patterns/k8s.md"
    - "Terraform (AWS)" : "patterns/terraform.md"
    - "Terraform (aliyun)" : "patterns/terraform_aliyun.md"
    - "Personal Config" : "patterns/personal_config.md"
  - wmax641 App Platform (WAP):
    - "IAM and Accounts" : "wap/iam_accounts.md"
    - "Legacy IAM State" : "wap/iam_legacy.md"
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.indexes
    #- navigation.sections
    #- navigation.tabs
    #- navigation.expand
    - content.code.copy
  extra:
    homepage: https://wmax641.website
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
