site_name: wmax641's docs
site_url: https://wmax641.website/personal-docs/
site_author: wmax641
site_description: wmax641's personal docs and notes
nav:
  - Systems Administration:
    - "Shell cheatsheet" : "sysadmin/shell_cheatsheet.md"
    - "jq cheatsheet" : "sysadmin/jq_cheatsheet.md"
    - "Docker" : "sysadmin/docker.md"
    - "K8s" : "sysadmin/k8s.md"
    - "Certificates and OpenSSL" : "sysadmin/certs.md"
  - Linux Systems Administration:
    - "Wireguard" : "linux/wireguard.md"
  - Boilerplate Code:
    - "Dockerfile" : "boilerplate/docker.md"
    - "Terraform (AWS)" : "boilerplate/terraform.md"
    - "Terraform (aliyun)" : "boilerplate/terraform_aliyun.md"
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.indexes
    #- navigation.sections
    #- navigation.tabs
    #- navigation.expand
    - content.code.copy
  extra:
    homepage: https://wmax641.website
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
